variables:
- template: templates/vars.yml

trigger:
  branches:
    include:
    - master
    - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: templates/build-test-steps.yml

- task: CopyFiles@2
  displayName: Copy dist folder
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: Publish artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Docker@2
  displayName: Build and push an image to ACR
  inputs:
    repository: fish-front
    Dockerfile: Dockerfile
    containerRegistry: FishFinderHub
    tags: |
          $(Build.BuildId)
          latest
